package main

import (
	"database/sql"
	"fmt"
	"net/http"
	"os"
	"sync/atomic"

	"github.com/Gibbsface/chirpy.git/internal/database"
	"github.com/joho/godotenv"
	_ "github.com/lib/pq"
)

type Config struct {
	platform       string
	fileserverHits atomic.Int32
	db             *database.Queries
	secret         string
}

func main() {
	//load env variables from .env
	godotenv.Load()
	dbURL := os.Getenv("DB_URL")

	// open the db connection
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		fmt.Printf("Error opening db connection: %v\n", err)
		os.Exit(1)
	}

	//create a new dbQueries object from the db pointer
	// db is *sql.DB, a connection that we just opened
	// database is an internal package that was generated by sqlc. We need to hook up this package into our config
	dbQueries := database.New(db)

	// initialize server config state
	cfg := Config{
		fileserverHits: atomic.Int32{},
		db:             dbQueries,
		platform:       os.Getenv("PLATFORM"),
		secret:         os.Getenv("SECRET"),
	}

	//Create serverMux and register handlers
	sMux := http.NewServeMux()

	//admin
	sMux.HandleFunc("GET /admin/metrics", cfg.AdminMetrics)
	sMux.HandleFunc("POST /admin/reset", cfg.AdminReset)

	//GET
	sMux.HandleFunc("GET /api/healthz", ApiHealthz)
	sMux.HandleFunc("GET /api/chirps", cfg.ApiGetAllChirps)
	sMux.HandleFunc("GET /api/chirps/{chirpID}", cfg.ApiGetChirp)

	// POST
	sMux.HandleFunc("POST /api/chirps", cfg.ApiCreateChirp)
	sMux.HandleFunc("POST /api/users", cfg.ApiCreateUser)
	sMux.HandleFunc("POST /api/login", cfg.ApiLogin)
	sMux.HandleFunc("POST /api/refresh", cfg.ApiRefresh)
	sMux.HandleFunc("POST /api/revoke", cfg.ApiRevoke)

	// file server handler
	fsHandler := http.StripPrefix("/app", http.FileServer(http.Dir(".")))
	sMux.Handle("/app/", cfg.MiddlewareMetricsInc(fsHandler))

	// initialize server struct and start serving
	s := &http.Server{
		Addr:    ":8080",
		Handler: sMux,
	}

	s.ListenAndServe()

}
